site_name: IT Manual, Since:26.1.30

theme:
#  name: mkdocs  # 기본 테마 사용 (명시적으로 설정)
  name: material  # 코드 입력

markdown_extensions:
  - md_in_html
  - attr_list

nav:
  - Home: index.md
  - User Guide:
      - 사용 방법: 01_PyCom.md
      - 안내문서 메인: 02_user_guide.md
      - 설치 가이드: 03_install.md
      

